/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

GacGen.exe Resource.xml

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#ifndef VCZH_WORKFLOW_COMPILER_GENERATED_CODEBOOKWINDOW
#define VCZH_WORKFLOW_COMPILER_GENERATED_CODEBOOKWINDOW

#include "GacPassPartialClasses.h"

#if defined( _MSC_VER)
#pragma warning(push)
#pragma warning(disable:4250)
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wparentheses-equality"
#elif defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wparentheses-equality"
#endif

namespace gacpass
{
	class CodeBookWindow : public ::vl::presentation::controls::GuiCustomControl, public ::gacpass::CodeBookWindowConstructor, public ::vl::reflection::Description<CodeBookWindow>
	{
		friend class ::gacpass::CodeBookWindowConstructor;
#ifndef VCZH_DEBUG_NO_REFLECTION
		friend struct ::vl::reflection::description::CustomTypeDescriptorSelector<CodeBookWindow>;
#endif
	public:
		CodeBookWindow();
		~CodeBookWindow();
	};

}
#if defined( _MSC_VER)
#pragma warning(pop)
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#elif defined(__clang__)
#pragma clang diagnostic pop
#endif

#endif
