/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

GacGen.exe Resource.xml

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#ifndef VCZH_WORKFLOW_COMPILER_GENERATED_GACPASS
#define VCZH_WORKFLOW_COMPILER_GENERATED_GACPASS

#include "GacPassPartialClasses.h"
#include "CodeBookWindow.h"
#include "LoginWindow.h"

#endif
