/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

GacGen.exe Resource.xml

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#include "GacPassReflection.h"

#if defined( _MSC_VER)
#pragma warning(push)
#pragma warning(disable:4250)
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wparentheses-equality"
#elif defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wparentheses-equality"
#endif

/***********************************************************************
Reflection
***********************************************************************/

namespace vl
{
	namespace reflection
	{
		namespace description
		{
#ifndef VCZH_DEBUG_NO_REFLECTION
			IMPL_CPP_TYPE_INFO(gacpass::CodeBookWindow)
			IMPL_CPP_TYPE_INFO(gacpass::CodeBookWindowConstructor)
			IMPL_CPP_TYPE_INFO(gacpass::IRegisterViewModel)
			IMPL_CPP_TYPE_INFO(gacpass::IViewModel)
			IMPL_CPP_TYPE_INFO(gacpass::LoginWindow)
			IMPL_CPP_TYPE_INFO(gacpass::LoginWindowConstructor)
			IMPL_CPP_TYPE_INFO(gacpass::MainWindow)
			IMPL_CPP_TYPE_INFO(gacpass::MainWindowConstructor)
			IMPL_CPP_TYPE_INFO(gacpass::RegisterWindow)
			IMPL_CPP_TYPE_INFO(gacpass::RegisterWindowConstructor)

#define _ ,
			BEGIN_CLASS_MEMBER(::gacpass::CodeBookWindow)
				CLASS_MEMBER_BASE(::vl::presentation::controls::GuiCustomControl)
				CLASS_MEMBER_BASE(::gacpass::CodeBookWindowConstructor)
				CLASS_MEMBER_CONSTRUCTOR(::gacpass::CodeBookWindow*(), NO_PARAMETER)
			END_CLASS_MEMBER(::gacpass::CodeBookWindow)

			BEGIN_CLASS_MEMBER(::gacpass::CodeBookWindowConstructor)
				CLASS_MEMBER_BASE(::vl::reflection::DescriptableObject)
				CLASS_MEMBER_CONSTRUCTOR(::vl::Ptr<::gacpass::CodeBookWindowConstructor>(), NO_PARAMETER)
				CLASS_MEMBER_METHOD(__vwsn_gacpass_CodeBookWindow_Initialize, { L"__vwsn_this_" })
				CLASS_MEMBER_FIELD(__vwsn_precompile_0)
				CLASS_MEMBER_FIELD(__vwsn_precompile_1)
				CLASS_MEMBER_FIELD(__vwsn_precompile_2)
				CLASS_MEMBER_FIELD(__vwsn_precompile_3)
				CLASS_MEMBER_FIELD(__vwsn_precompile_4)
			END_CLASS_MEMBER(::gacpass::CodeBookWindowConstructor)

			BEGIN_INTERFACE_MEMBER(::gacpass::IRegisterViewModel)
				CLASS_MEMBER_BASE(::vl::reflection::IDescriptable)
				CLASS_MEMBER_METHOD(GetConfirmPassword, NO_PARAMETER)
				CLASS_MEMBER_METHOD(GetConfirmPasswordError, NO_PARAMETER)
				CLASS_MEMBER_METHOD(GetPassword, NO_PARAMETER)
				CLASS_MEMBER_METHOD(GetPasswordError, NO_PARAMETER)
				CLASS_MEMBER_METHOD(SetConfirmPassword, { L"__vwsn_value_" })
				CLASS_MEMBER_METHOD(SetPassword, { L"__vwsn_value_" })
				CLASS_MEMBER_EVENT(ConfirmPasswordChanged)
				CLASS_MEMBER_EVENT(ConfirmPasswordErrorChanged)
				CLASS_MEMBER_EVENT(PasswordChanged)
				CLASS_MEMBER_EVENT(PasswordErrorChanged)
				CLASS_MEMBER_PROPERTY_EVENT(ConfirmPassword, GetConfirmPassword, SetConfirmPassword, ConfirmPasswordChanged)
				CLASS_MEMBER_PROPERTY_EVENT_READONLY(ConfirmPasswordError, GetConfirmPasswordError, ConfirmPasswordErrorChanged)
				CLASS_MEMBER_PROPERTY_EVENT(Password, GetPassword, SetPassword, PasswordChanged)
				CLASS_MEMBER_PROPERTY_EVENT_READONLY(PasswordError, GetPasswordError, PasswordErrorChanged)
			END_INTERFACE_MEMBER(::gacpass::IRegisterViewModel)

			BEGIN_INTERFACE_MEMBER(::gacpass::IViewModel)
				CLASS_MEMBER_BASE(::vl::reflection::IDescriptable)
				CLASS_MEMBER_METHOD(GetLoggedIn, NO_PARAMETER)
				CLASS_MEMBER_METHOD(GetMainPasswordSet, NO_PARAMETER)
				CLASS_MEMBER_METHOD(GetRegisterViewModel, NO_PARAMETER)
				CLASS_MEMBER_PROPERTY_READONLY(LoggedIn, GetLoggedIn)
				CLASS_MEMBER_PROPERTY_READONLY(MainPasswordSet, GetMainPasswordSet)
				CLASS_MEMBER_PROPERTY_READONLY(RegisterViewModel, GetRegisterViewModel)
			END_INTERFACE_MEMBER(::gacpass::IViewModel)

			BEGIN_CLASS_MEMBER(::gacpass::LoginWindow)
				CLASS_MEMBER_BASE(::vl::presentation::controls::GuiCustomControl)
				CLASS_MEMBER_BASE(::gacpass::LoginWindowConstructor)
				CLASS_MEMBER_CONSTRUCTOR(::gacpass::LoginWindow*(), NO_PARAMETER)
			END_CLASS_MEMBER(::gacpass::LoginWindow)

			BEGIN_CLASS_MEMBER(::gacpass::LoginWindowConstructor)
				CLASS_MEMBER_BASE(::vl::reflection::DescriptableObject)
				CLASS_MEMBER_CONSTRUCTOR(::vl::Ptr<::gacpass::LoginWindowConstructor>(), NO_PARAMETER)
				CLASS_MEMBER_METHOD(__vwsn_gacpass_LoginWindow_Initialize, { L"__vwsn_this_" })
				CLASS_MEMBER_FIELD(__vwsn_precompile_0)
				CLASS_MEMBER_FIELD(__vwsn_precompile_1)
				CLASS_MEMBER_FIELD(__vwsn_precompile_2)
				CLASS_MEMBER_FIELD(__vwsn_precompile_3)
				CLASS_MEMBER_FIELD(__vwsn_precompile_4)
			END_CLASS_MEMBER(::gacpass::LoginWindowConstructor)

			BEGIN_CLASS_MEMBER(::gacpass::MainWindow)
				CLASS_MEMBER_BASE(::vl::presentation::controls::GuiWindow)
				CLASS_MEMBER_BASE(::gacpass::MainWindowConstructor)
				CLASS_MEMBER_CONSTRUCTOR(::gacpass::MainWindow*(::vl::Ptr<::gacpass::IViewModel>), { L"__vwsn_ctor_parameter_ViewModel" })
				CLASS_MEMBER_METHOD(GetViewModel, NO_PARAMETER)
				CLASS_MEMBER_FIELD(__vwsn_parameter_ViewModel)
				CLASS_MEMBER_PROPERTY_READONLY(ViewModel, GetViewModel)
			END_CLASS_MEMBER(::gacpass::MainWindow)

			BEGIN_CLASS_MEMBER(::gacpass::MainWindowConstructor)
				CLASS_MEMBER_BASE(::vl::reflection::DescriptableObject)
				CLASS_MEMBER_CONSTRUCTOR(::vl::Ptr<::gacpass::MainWindowConstructor>(), NO_PARAMETER)
				CLASS_MEMBER_METHOD(__vwsn_gacpass_MainWindow_Initialize, { L"__vwsn_this_" })
				CLASS_MEMBER_FIELD(__vwsn_precompile_0)
				CLASS_MEMBER_FIELD(__vwsn_precompile_1)
				CLASS_MEMBER_FIELD(__vwsn_precompile_2)
				CLASS_MEMBER_FIELD(__vwsn_precompile_3)
				CLASS_MEMBER_FIELD(ViewModel)
			END_CLASS_MEMBER(::gacpass::MainWindowConstructor)

			BEGIN_CLASS_MEMBER(::gacpass::RegisterWindow)
				CLASS_MEMBER_BASE(::vl::presentation::controls::GuiCustomControl)
				CLASS_MEMBER_BASE(::gacpass::RegisterWindowConstructor)
				CLASS_MEMBER_CONSTRUCTOR(::gacpass::RegisterWindow*(::vl::Ptr<::gacpass::IRegisterViewModel>), { L"__vwsn_ctor_parameter_ViewModel" })
				CLASS_MEMBER_METHOD(GetViewModel, NO_PARAMETER)
				CLASS_MEMBER_FIELD(__vwsn_parameter_ViewModel)
				CLASS_MEMBER_PROPERTY_READONLY(ViewModel, GetViewModel)
			END_CLASS_MEMBER(::gacpass::RegisterWindow)

			BEGIN_CLASS_MEMBER(::gacpass::RegisterWindowConstructor)
				CLASS_MEMBER_BASE(::vl::reflection::DescriptableObject)
				CLASS_MEMBER_CONSTRUCTOR(::vl::Ptr<::gacpass::RegisterWindowConstructor>(), NO_PARAMETER)
				CLASS_MEMBER_METHOD(__vwsn_gacpass_RegisterWindow_Initialize, { L"__vwsn_this_" })
				CLASS_MEMBER_FIELD(__vwsn_precompile_0)
				CLASS_MEMBER_FIELD(__vwsn_precompile_1)
				CLASS_MEMBER_FIELD(__vwsn_precompile_10)
				CLASS_MEMBER_FIELD(__vwsn_precompile_11)
				CLASS_MEMBER_FIELD(__vwsn_precompile_12)
				CLASS_MEMBER_FIELD(__vwsn_precompile_13)
				CLASS_MEMBER_FIELD(__vwsn_precompile_14)
				CLASS_MEMBER_FIELD(__vwsn_precompile_2)
				CLASS_MEMBER_FIELD(__vwsn_precompile_3)
				CLASS_MEMBER_FIELD(__vwsn_precompile_4)
				CLASS_MEMBER_FIELD(__vwsn_precompile_5)
				CLASS_MEMBER_FIELD(__vwsn_precompile_6)
				CLASS_MEMBER_FIELD(__vwsn_precompile_7)
				CLASS_MEMBER_FIELD(__vwsn_precompile_8)
				CLASS_MEMBER_FIELD(__vwsn_precompile_9)
				CLASS_MEMBER_FIELD(ViewModel)
				CLASS_MEMBER_FIELD(self)
				CLASS_MEMBER_FIELD(textBoxConfirmPassword)
				CLASS_MEMBER_FIELD(textBoxPassword)
			END_CLASS_MEMBER(::gacpass::RegisterWindowConstructor)

#undef _
			class GacPassTypeLoader : public Object, public ITypeLoader
			{
			public:
				void Load(ITypeManager* manager)
				{
					ADD_TYPE_INFO(::gacpass::CodeBookWindow)
					ADD_TYPE_INFO(::gacpass::CodeBookWindowConstructor)
					ADD_TYPE_INFO(::gacpass::IRegisterViewModel)
					ADD_TYPE_INFO(::gacpass::IViewModel)
					ADD_TYPE_INFO(::gacpass::LoginWindow)
					ADD_TYPE_INFO(::gacpass::LoginWindowConstructor)
					ADD_TYPE_INFO(::gacpass::MainWindow)
					ADD_TYPE_INFO(::gacpass::MainWindowConstructor)
					ADD_TYPE_INFO(::gacpass::RegisterWindow)
					ADD_TYPE_INFO(::gacpass::RegisterWindowConstructor)
				}

				void Unload(ITypeManager* manager)
				{
				}
			};
#endif

			bool LoadGacPassTypes()
			{
#ifndef VCZH_DEBUG_NO_REFLECTION
				if (auto manager = GetGlobalTypeManager())
				{
					return manager->AddTypeLoader(MakePtr<GacPassTypeLoader>());
				}
#endif
				return false;
			}
		}
	}
}

#if defined( _MSC_VER)
#pragma warning(pop)
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#elif defined(__clang__)
#pragma clang diagnostic pop
#endif
